### PR TITLE
fix: Uplift code to running state

### LINKED ISSUE #14: Uplift code to running state
Update Python dependencies, run API
Update Node dependencies
Install Vite since CRA is deprecated (or on notice)
Change connection details where relevant to talk to local mongo instance

### PR DESCRIPTION
**Pull request by chriswtodd**
Closes #14

### CODE REVIEW

File: src/d3/tooltipMixin.js [hunk 1]
```diff
@@ -3,206 +3,206 @@
...
-                    .style("display", "none");
-                d3.selectAll(".plot-rect")
-                    .attr("height", 1)
-                    .style("opacity", 0)
-            }
-        })
-    }
-}
\ No newline at end of file
+ import * as d3 from "d3";
```
Comment (chriswtodd) [inline src/d3/tooltipMixin.js:6]: formatting

File: mongo_processor.py [hunk 2]
```diff
@@ -11,12 +11,13 @@
 load_dotenv()
 user = os.environ['MONGO_USER']
 password = os.environ['MONGO_PASS']
-mongo_online = MongoClient("mongodb+srv://{0}:{1}@cluster0-9mebh.mongodb.net/test?retryWrites=true&w=majority".format(user, password))
+mongo_local = MongoClient("mongodb://localhost:27017/test?retryWrites=true&w=majority")
```
Comment (chriswtodd) [inline mongo_processor.py:14]: https://github.com/chriswtodd/BusEmissionsVis/issues/19
